### ISSUE TITLE
Drop Spring Boot 2.x support as it is not longer supported by the spring community

### ISSUE THREAD

**Issue by salaboy** [dapr/java-sdk#1039]
## Expected Behavior

We should focus on maintaining and improving Spring Boot 3.x support as the default Spring Boot integration, as the 2.x release branch has already reached the "end of life" phase -> https://spring.io/projects/spring-boot#support 

## Actual Behavior

The main spring boot integration is still on spring boot 2.x

## Release Note

RELEASE NOTE:

**Comment by salaboy** [comment]
@artursouza but even if community members depend on springboot 2.x nobody from the springboot community will even answers about 2.x, as it reached end of life.

**Comment by ThomasVitale** [comment]
I like this proposal. Spring Boot 2 reached end of like on 2023-11-24 and the Spring users had a long time to upgrade since it was announced in 2022 already. If there's any security vulnerability found in that version, they will not be fixed since it's out of support. And there's a risk that Dapr will inherit them if building on that old version.
