### ISSUE TITLE
[WONTFIX] Use Gradle instead of Maven as build tool

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#15]
## Move to Gradle for build

I used Maven and Gradle in the past (not recent, though). I see Gradle has some benefits over Maven:
+ Faster build for same tasks.
+ Syntax in Groovy instead of XML.
+ UX is command-line first instead of IDE first.
+ Better dependency conflict resolution.

https://gradle.org/maven-vs-gradle/

**Comment by deemkeen** [comment]
I highly disagree on Grade being a better build tool.

- Regular Java developers don't know Groovy
- Maven pom.xml is declarative, which is good for configurations, Gradle gives you too much freedom here
- The plugin variety and support is better in Maven
- The tooling support is also better

**Comment by brunoborges** [comment]
True. Maven is well known by most Java developers and unless you seek less contributions, you should stick to Maven.

1. Faster built time with Gradle is really only interesting if you are going to get Gradle Enterprise (paid) on a CICD environment. Otherwise, there isn't much value. Besides, this project is small.
1. Groovy syntax can be great for experienced developers. XML configuration for Maven is by convention and understood by hundreds of thousands of developers
1. UX with Maven works just fine from the CLI as much as Gradle. 
1. Gradle uses Maven artifacts. Dependency management is pretty much the same.

**Comment by brunoborges** [comment]
Another important note is that Gradle does not support Java modularity (Java 9+ JPMS), Maven does.

You may want to ping @jonathangiles, the Java Architect of the Azure SDKs for more input on Gradle vs Maven.

**Comment by artursouza** [comment]
The deal breaker to use Gradle, IMO, is that it is not widely used in the Java community. We want to avoid creating artificial barriers for contributors.

Unless anyone has strong arguments pro Gradle, we will post-pone this change.

**Comment by amanbha** [comment]
> The deal breaker to use Gradle, IMO, is that it is not widely used in the Java community. We want to avoid creating artificial barriers for contributors.
> 
> Unless anyone has strong arguments pro Gradle, we will post-pone this change.

Agree with this decision, low friction for devs.
