### ISSUE TITLE
What should be the minimum Java version supported by Dapr SDK?

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#17]
** What should be the minimum Java version supported by Dapr SDK?

I recommend Java 8 since it is the previous LTS version and still the most used version. Java 11 is the latest LTS version.

https://www.jetbrains.com/lp/devecosystem-2019/java/

**Comment by amanbha** [comment]
I propose to use the latest version Java 11, since this project is starting fresh, lets use the latest version, Once we start supporting Java8, we will have to support it for the foreseeable future.  We can talk to customers who are using older Java version to understand the issues in upgrading . If there is a tremendous need for it, then we can switch back to Java 8.
For dotnet, we chose to use latest .netcore 3.0.

**Comment by artursouza** [comment]
My concern is to hurt adoption by not being compatible with Java 8. On the other hand, for apps that are still in Java 8, how realistic is it to expect them to use Dapr? There might be some legacy apps there nobody wants to touch. I see both sides.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JonathanGiles** [comment]
I would recommend Java 8. It is unfortunate, but it is the right choice right now. It is the baseline we are using for all Azure SDKs.

**Comment by artursouza** [comment]
We have decided to go with Java 8 for the Dapr SDK and Java 11 in the examples.

**Comment by amanbha** [comment]
@artursouza Could you please add a decision record for this under https://github.com/dapr/dapr/tree/master/docs/decision_records/sdk and link it in this .md https://github.com/dapr/dapr/blob/master/docs/decision_records/decision_records.md
