### ISSUE TITLE
[java-sdk] Code coverage

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#20]
* Check for code coverage in Java SDK and output current line and branch coverage.
* Fail build if line or branch coverage is < 80% (examples excluded)

* Keep coverage threshold under 80% for this issue. We will switch to 80% in the end.

**Comment by JuanJose-Herrera** [comment]
I add the JaCoCo tool in the PR https://github.com/dapr/java-sdk/pull/67 that helps to measure the coverage of the unit testing, but right now the rules are disabled in order to allow the project to compile successfully and to be able to compile the examples. We will need to enable these rules in the near feature when we have more unit tests for all the code.
