### ISSUE TITLE
Execute all samples from the same folder

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/java-sdk#223]
## Describe the proposal

Currently some samples are executed from the root like the HTTP Invoke 
```
dapr run --app-id invokedemo --app-port 3000 --port 3005 -- mvn exec:java -pl=examples ...
```

and some are executed inside the examples folder like the Bindings sample
```
cd to [repo-root]/examples
dapr run --app-id inputbinding --app-port 3000 --port 3005 -- mvn exec:java -D exec.mainClass=io.dapr.examples.bindings.http.InputBindingExample -D exec.args="-p 3000"
```

this not only confuses, it also leads to a new components folder generation in the root which is unnecessary.

**Comment by LMWF** [comment]
Agreed it would be better to have a single location.  But the reason the instructions for the bindings sample say to cd into `examples` is because this sample uses kafka and there is a component yaml for kafka in `examples/components`.

Installing kafka is a bit heavier than the components used in the other examples so that's why it was separated this way.

We could:
1. look into some more flexible way (e.g. perhaps allow the user to specify location of components folder)
2. use a different type of binding component for this example that is more lightweight.

**Comment by JMayrbaeurl** [comment]
I would prefer to have a dedicated folder for each example, maybe using a common Maven parent for generic setup. This would remove the confusion on the different ways to execute them and give the possiblity to easily add or change the Dapr components for the example.
