### ISSUE TITLE
Remove dependency from OpenTelemetry SDK - still unstable

### ISSUE THREAD

**Issue by xiazuojie** [dapr/java-sdk#453]
## UPDATE

Remove dependency from OpenTelemetry SDK completely, a consequence of that is the fix described below.

Keep OpenTelemetrySDK in example only.

## Describe the proposal
Currently, ``io.dapr.client.domain.Response`` is in a lot of State APIs.
```java
<T> Mono<Response<List<State<T>>>> getBulkState(GetBulkStateRequest request, TypeRef<T> type);

Mono<Response<Void>> saveBulkState(SaveStateRequest request);
```
The sole purpose of a Response is to hold a ``io.opentelemetry.context.Context`` and the object. However, project reactor already has an integrated [reactor.util.context.Context](https://projectreactor.io/docs/core/release/reference/#context), which serves the same purpose of ``io.opentelemetry.context.Context``, i.e.  carry scoped-values across API boundaries and between threads.

I suggest remove ``io.dapr.client.domain.Response`` altogether and use ``reactor.util.context.Context``.

**Comment by artursouza** [comment]
@xiazuojie This started an interesting discussion. Our SDK depends on OpenTelemetry v0.10.0. Since OpenTelemetry is not stable yet, it is not compatible with version 0.14.0. It also means that we force apps to use the same OpenTelemetry SDK version as we do - this is a problem for us to call our SDK "stable". We will work on this issue with urgency but the scope is bigger: we want to remove dependency from OpenTelemetry SDK.

**Comment by artursouza** [comment]
@xiazuojie I am about to create a PR removing opentelemetry and opencensus as a dependency for the sdk (examples will still use that). I wonder if the Response object can actually be removed. I was looking into how to do it with Reactor only but it seems that the Context must be set *after* the reader of the Context in the chain. It is odd, I am not sure why. I reproduced it with the example discussed here: https://stackoverflow.com/questions/54779831/mono-subscribercontext-returning-old-context

it means that it would not be possible because it would require applications to pass in their mono object as an input (see example above).

In the mean time, I will keep Response class but with the reactor's Context instead.

Removing Response would still be a breaking change if we decide to go that way. Please, let me know if you have an idea on how to remove the Response class and use reactor only.

**Comment by artursouza** [comment]
@xiazuojie We closed this issue since we removed dependency from OpenTelemetry and OpenCensus SDKs. See my comment above regarding removing `Response` object. I am happy to reopen this issue and discuss it further.

**Comment by xiazuojie** [comment]
@artursouza, thanks for the reply. I still do not think this [commit](https://github.com/dapr/java-sdk/pull/463) is best way to implement "context".

Let's think about why do we need a context. "To carry scoped-values across API boundaries and between threads", what does it means?
* carry scoped-values across API boundaries: this means context should NOT be part of the API, i.e. context should not be in an API's the input arguments or its return value and still be accessible everywhere. In current implementation, the context is in both Response and GetStateRequest classes, meaning it's part of the API.
* carry scoped-values between threads: if context is not part of the API, how can we access it? For imperative (blocking) programming, it's simple: put context in some global ThreadLocal variables, then it can be access everywhere. However, when it comes to reactive programming, global ThreadLocal variables no longer works because a reactive stream can run in other threads. For this reason, project reactor includes a [reactor.util.context.Context](https://projectreactor.io/docs/core/release/reference/#context) in order to "carry scoped-values between threads".

Back to dapr, how to we implement context? Basically, just follow the intended usage of [reactor.util.context.Context](https://projectreactor.io/docs/core/release/reference/#context).

change the API from
``` java
<T> Mono<Response<State<T>>> getState(GetStateRequest request, TypeRef<T> type);
```
to
```java
<T> Mono<State<T>> getState(GetStateRequest request, TypeRef<T> type);
```
also, remove context field from GetStateRequest.

## For client, put values into context.
```java
daprClient.getState(request, TypeRef.STRING).subscriberContext(it -> it.put("grpc-trace-bin", "foo").put("traceparent", "bar").put("tracestate", "foobar"));
```
## For DaprClientGrpc, to get values from context.
```java
public <T> Mono<State<T>> getState(GetStateRequest request, TypeRef<T> type) {
....
        return Mono.subscriberContext().zip(
           Mono.just("abc"),
           context, value -> {
                 context.get("grpc-trace-bin")
                 ....
           }
        )
}
```

I can PR if you agree with this design.

**Comment by artursouza** [comment]
Please, send a PR with one method using this proposal. Use the tracing example as a way to validate this. We are in a time crunch. We can still squeeze in a breaking change but must be done within this week.

— Artur Souza
________________________________

**Comment by xiazuojie** [comment]
@artursouza please take a look at https://github.com/dapr/java-sdk/pull/476

**Comment by artursouza** [comment]
That is great! We will incorporate the PR. Please, see comments there. Let's track the issue to remove Context from API in a separate issue. I am creating one.

**Comment by artursouza** [comment]
Issue to track removal of Context is now in the issue linked above.
