### ISSUE TITLE
why metadata not use inf this function

### ISSUE THREAD

**Issue by ansjsun** [dapr/java-sdk#660]
https://github.com/dapr/java-sdk/blob/05bf66e0d4964b6588e8c5865c7902c53c89d636/sdk/src/main/java/io/dapr/client/AbstractDaprClient.java#L100

public <T> Mono<T> invokeMethod(String appId, String methodName, Object data, HttpExtension httpExtension, Map<String, String> metadata, TypeRef<T> type) {
        InvokeMethodRequest req = (new InvokeMethodRequest(appId, methodName)).setBody(data).setHttpExtension(httpExtension).setContentType(this.objectSerializer.getContentType());
        return this.invokeMethod(req, type);
    }

**Comment by artursouza** [comment]
> https://github.com/dapr/java-sdk/blob/05bf66e0d4964b6588e8c5865c7902c53c89d636/sdk/src/main/java/io/dapr/client/AbstractDaprClient.java#L100
> 
> public Mono invokeMethod(String appId, String methodName, Object data, HttpExtension httpExtension, Map<String, String> metadata, TypeRef type) { InvokeMethodRequest req = (new InvokeMethodRequest(appId, methodName)).setBody(data).setHttpExtension(httpExtension).setContentType(this.objectSerializer.getContentType()); return this.invokeMethod(req, type); }

This method should be deprecated. The metadata does not make sense because it is not a concept in service invocation. Service invocation is protocol specific and we cannot abstract both gRPC and HTTP into a common interface.

I would also suggest we deprecate all invokeMethod methods and make it HTTP specific methods instead, so applications know this is an HTTP only call.

For gRPC, Dapr already has a solution that does not benefit from SDK at all: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/#step-2-invoke-the-service

**Comment by ansjsun** [comment]
thx for reply .
